### ISSUE TITLE
Disable slot in lobby

### ISSUE THREAD

**Issue by ozonex** [FAForever/lobby#151]
Right now there is only option to lock slot. It's ok when we want to save it for someone.

Will be good to add option to disable slot, when we want to play eg. 2v2 on map for 8 players.
This option should work like lock slot, but it should also reduce max amount of players shown in game description.
Then when we will disable 4 slots on 8 players map it should show that there are [X]/4 players, not [X]/8.

**Comment by Sheeo** [comment]
Closing this. Any more relevant discussion should go at FAForever/fa.
