### ISSUE TITLE
All replays crashing

### ISSUE THREAD

**Issue by escii** [FAForever/lobby#160]
Got this error while loading a local replay... 

**FAF Username:** escii

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\escii\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by Sheeo** [comment]
Thanks for reporting this! It is not going to be a problem in the next lobby update, and likely just an issue with releasing the current patch.

Can you try restarting and updating again?

**Comment by escii** [comment]
There is the dump from the game itself... if it helps

Update started at 2015-01-05 03:28:05
Using game path: C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance
Using appdata: C:\ProgramData\FAForever
Connected to update server at 2015-01-05 03:28:05
writeToServer(GET_FILES_TO_UPDATE, [FAF])
handleAction(LIST_FILES_TO_UP) - 324 bytes
Files to update: [ForgedAlliance.exe, init_faf.lua, init_ladder1v1.lua, GDFBinary.dll, SupComDataPath.lua, SupComDataPathFAF.lua, init_nonxt.lua]
writeToServer(PATCH_TO, [bin, init_nonxt.lua, 16da7063ae3309c154a2c544f559b3a9, 3637])
writeToServer(PATCH_TO, [bin, GDFBinary.dll, 6f57f59c2e705d7a5a02d49e3915cb26, 3637])
writeToServer(PATCH_TO, [bin, init_faf.lua, e1fede1183ca3f06bb6031fdc93823b3, 3637])
writeToServer(PATCH_TO, [bin, ForgedAlliance.exe, 4f023b90923ff14491ededd6c825c4ec, 3637])
writeToServer(PATCH_TO, [bin, SupComDataPath.lua, 55ac1ef97845f2291da64b830299331e, 3637])
writeToServer(PATCH_TO, [bin, SupComDataPathFAF.lua, 962c9d1327657d77184adcf358c628f1, 3637])
writeToServer(PATCH_TO, [bin, init_ladder1v1.lua, ea96ac9cec88af29c08556c96465acfe, 3637])
handleAction(UP_TO_DATE) - 56 bytes
file : init_nonxt.lua
init_nonxt.lua is up to date.
handleAction(UP_TO_DATE) - 54 bytes
file : GDFBinary.dll
GDFBinary.dll is up to date.
handleAction(UP_TO_DATE) - 52 bytes
file : init_faf.lua
init_faf.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : ForgedAlliance.exe
ForgedAlliance.exe is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : SupComDataPath.lua
SupComDataPath.lua is up to date.
handleAction(UP_TO_DATE) - 70 bytes
file : SupComDataPathFAF.lua
SupComDataPathFAF.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : init_ladder1v1.lua
init_ladder1v1.lua is up to date.
Updates applied successfully.
writeToServer(GET_FILES_TO_UPDATE, [FAFGAMEDATA])
handleAction(LIST_FILES_TO_UP) - 352 bytes
Files to update: [faforever.faf, effects.nx2, env.nx2, loc.nx2, lua.nx2, meshes.nx2, modules.nx2, projectiles.nx2, schook.nx2, textures.nx2, units.nx2]
writeToServer(PATCH_TO, [gamedata, schook.nx2, 40d5c5fe016b2eafefc2b759172806c9, 3637])
writeToServer(PATCH_TO, [gamedata, effects.nx2, df11b1cc8eeaed0e21fa5b023228300c, 3637])
writeToServer(PATCH_TO, [gamedata, modules.nx2, 746f1db8f321e4c6ed0be448557ca073, 3637])
writeToServer(PATCH_TO, [gamedata, lua.nx2, d41d8cd98f00b204e9800998ecf8427e, 3637])
writeToServer(PATCH_TO, [gamedata, textures.nx2, 6d988f6224bbaf33b71d33c3c15f4448, 3637])
writeToServer(PATCH_TO, [gamedata, env.nx2, c8e06a7315aa17c5ed7e2cc6d6ecee99, 3637])
writeToServer(PATCH_TO, [gamedata, meshes.nx2, e5dbdaf65e7820b60a398eb98136fa4c, 3637])
writeToServer(PATCH_TO, [gamedata, faforever.faf, 51c196294638c22071dc8ee01e55771e, 3637])
writeToServer(PATCH_TO, [gamedata, loc.nx2, b761276596401c04dac01c81463891c3, 3637])
writeToServer(PATCH_TO, [gamedata, projectiles.nx2, a20c07ca43cab1624cb9d75c804a3b23, 3637])
writeToServer(PATCH_TO, [gamedata, units.nx2, 7c66db67cb2c72ffcb8e0984915f8012, 3637])
handleAction(UP_TO_DATE) - 48 bytes
file : schook.nx2
schook.nx2 is up to date.
handleAction(UP_TO_DATE) - 50 bytes
file : effects.nx2
effects.nx2 is up to date.
handleAction(UP_TO_DATE) - 50 bytes
file : modules.nx2
modules.nx2 is up to date.
handleAction(VERSION_PATCH_NOT_FOUND) - 68 bytes
Error: Patch version 3637 not found for lua.nx2.
writeToServer(REQUEST_VERSION, [gamedata, lua.nx2, 3637])
handleAction(SEND_PATCH_URL) - 256 bytes
TIMEOUT: UpdaterTimeout(('Connection timed out while waiting for data.',))
Disconnected from server at 2015-01-05 03:32:21

**Comment by Sheeo** [comment]
Was fixed by deleting the cache directory.
