### ISSUE TITLE
Msi Installer isn't downloading properly

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/lobby#170]
Several people reported that on trying to download the installer for faf, their downloads stopped before halfway done.
Some people could use any browser to download it fine, others had problems with specific browsers (firefox) but then IE worked to download.

**Comment by Sheeo** [comment]
Is this persisting?

Moving it to FAForever/server#14

**Comment by VoRGoR** [comment]
I told all the people who were complaining about it to message me again or report it directly here.
Have got nothing so far, so it's probable it just was a temporary issue.

**Comment by Happydacat** [comment]
This is still an issue for me.

**Comment by anihilnine** [comment]
I downloaded the installer yesterday and it worked fine
