### ISSUE TITLE
wrong ip used for udp testing

### ISSUE THREAD

**Issue by fafafaf** [FAForever/lobby#182]
https://github.com/FAForever/lobby/blob/develop/src/client/_clientwindow.py#L1058

**Comment by Sheeo** [comment]
This line gets it right https://github.com/FAForever/lobby/blob/master/src/client/_clientwindow.py#L1023 before that happens.

This is being removed as part of the network update anyway, so that's fine.

**Comment by fafafaf** [comment]
Network update?
